In [22]:
import pandas as pd 
data = pd.read_csv("data.csv")
df = data.copy()
df.head()

,otel,konum,secenek,fiyat
0,doubletree by hilton moda,caferağa,sadece oda,4820
1,bof hotels ceo suites ataşehir,ümraniye,sadece oda,3297
2,doubletree by hilton i̇stanbul topkapı,esenler-bayrampaşa,sadece oda,2315
3,dedeman bostancı,i̇çerenköy,sadece oda,3070
4,swissotel the bosphorus istanbul,beşiktaş,sadece oda,7275

In [23]:
df.drop(["otel"],axis =1,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 585 entries, 0 to 584
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   konum    585 non-null    object
 1   secenek  585 non-null    object
 2   fiyat    585 non-null    int64
dtypes: int64(1), object(2)
memory usage: 13.8+ KB

In [24]:
df

                  konum       secenek  fiyat
0              caferağa    sadece oda   4820
1              ümraniye    sadece oda   3297
2    esenler-bayrampaşa    sadece oda   2315
3            i̇çerenköy    sadece oda   3070
4              beşiktaş    sadece oda   7275
..                  ...           ...    ...
580              galata    sadece oda   1000
581             beyoğlu  oda kahvaltı    791
582               fatih  oda kahvaltı   1250
583             kadıköy  oda kahvaltı   3040
584             beyoglu  oda kahvaltı   1110

[585 rows x 3 columns]

In [25]:
for i in['konum','secenek']:
    print("Column: ",i)
    print(df[i].unique())

Column:  konum
['caferağa' 'ümraniye' 'esenler-bayrampaşa' 'i̇çerenköy' 'beşiktaş'
 'pendik' 'kadıköy' 'etiler' 'maslak' 'gayrettepe' 'beylikdüzü'
 'ataköy marina' 'taksim' 'esentepe' 'harbiye' 'merter' 'silivri'
 'küçükçekmece' 'kazlıçeşme' 'gümüşsuyu' 'fatih' 'ataşehir' 'şişli'
 'bakırköy' 'tuzla' 'yıldız' 'bağcılar' 'avcılar' 'zeytinburnu' 'halkalı'
 'ortaköy' 'i̇stanbul sütlüce' 'bomonti' 'maltepe' 'altunizade mahallesi'
 'kumburgaz' 'levent' 'sultanahmet' 'beyoğlu' 'tarabya' 'beyoglu'
 'karaköy' 'ataköy' 'yenibosna' 'bayrampaşa' 'kaynarca' 'bostancı'
 'yeşilköy' 'mecidiyeköy' 'sirkeci' 'kurtköy' 'şile' 'kayışdağı'
 'kavacık mahallesi' 'osmanbey' 'topkapı' 'başakşehir'
 'kayabaşı mahallesi' 'kartal-pendik' 'küçükbakkalköy' 'dudullu osb'
 'beyazıt' 'fulya' 'laleli' 'eyüp' 'i̇stanbul bahçelievler'
 'çağlayan mahallesi' 'kağıthane' 'gungoren' 'tophane' 'sanayi mahallesi'
 'suadiye' 'esenyurt' 'bahcelievler' 'bahçelievler' 'kanlıca mahallesi'
 'aksaray' 'i̇stanbul anadolu yakası' 'asmalımescit'
 'şirinevler mahallesi' 'bagcilar' 'ağva' 'rasimpaşa' 'kumkapı'
 'i̇stanbul' 'sancaktepe' 'gaziosmanpaşa' 'galata' 'büyükada'
 'cevizli mahallesi' 'sarıyer' 'arnavutköy' 'asmalı mescit' 'kartal'
 'karaköy-haliç' 'cihangir' 'beylerbeyi' 'adalar' 'moda' 'büyükçekmece'
 'nişantaşı' 'i̇stanbul aksaray' 'atasehir' 'i̇stanbul boğazı' 'cağaloğlu'
 'beykoz' 'üsküdar' 'sultanahmet-sirkeci' 'cankurtaran']
Column:  secenek
['sadece oda' 'oda kahvaltı' 'açık büfe kahvaltı' 'izole oda kahvaltı'
 'ücretsiz akşam yemeği' 'her sabah kahve/hamur işi ürünler']

In [26]:
from sklearn.preprocessing import LabelEncoder  #sayısal veri verme

LE = LabelEncoder()
label_dict = {}
for i in['konum','secenek']:
    df[i] = LE.fit_transform(df[i])
    label_dict[i] = {label:encoded_label for label,encoded_label in zip(LE.classes_,LE.transform
     (LE.classes_))}

In [27]:
df

     konum  secenek  fiyat
0       30        4   4820
1      104        4   3297
2       36        4   2315
3       56        4   3070
4       25        4   7275
..     ...      ...    ...
580     43        4   1000
581     24        3    791
582     41        3   1250
583     57        3   3040
584     23        3   1110

[585 rows x 3 columns]

In [28]:
label_dict

{'konum': {'adalar': 0,
  'aksaray': 1,
  'altunizade mahallesi': 2,
  'arnavutköy': 3,
  'asmalı mescit': 4,
  'asmalımescit': 5,
  'ataköy': 6,
  'ataköy marina': 7,
  'atasehir': 8,
  'ataşehir': 9,
  'avcılar': 10,
  'ağva': 11,
  'bagcilar': 12,
  'bahcelievler': 13,
  'bahçelievler': 14,
  'bakırköy': 15,
  'bayrampaşa': 16,
  'bağcılar': 17,
  'başakşehir': 18,
  'beyazıt': 19,
  'beykoz': 20,
  'beylerbeyi': 21,
  'beylikdüzü': 22,
  'beyoglu': 23,
  'beyoğlu': 24,
  'beşiktaş': 25,
  'bomonti': 26,
  'bostancı': 27,
  'büyükada': 28,
  'büyükçekmece': 29,
  'caferağa': 30,
  'cankurtaran': 31,
  'cağaloğlu': 32,
  'cevizli mahallesi': 33,
  'cihangir': 34,
  'dudullu osb': 35,
  'esenler-bayrampaşa': 36,
  'esentepe': 37,
  'esenyurt': 38,
  'etiler': 39,
  'eyüp': 40,
  'fatih': 41,
  'fulya': 42,
  'galata': 43,
  'gayrettepe': 44,
  'gaziosmanpaşa': 45,
  'gungoren': 46,
  'gümüşsuyu': 47,
  'halkalı': 48,
  'harbiye': 49,
  'i̇stanbul': 50,
  'i̇stanbul aksaray': 51,
  'i̇stanbul anadolu yakası': 52,
  'i̇stanbul bahçelievler': 53,
  'i̇stanbul boğazı': 54,
  'i̇stanbul sütlüce': 55,
  'i̇çerenköy': 56,
  'kadıköy': 57,
  'kanlıca mahallesi': 58,
  'karaköy': 59,
  'karaköy-haliç': 60,
  'kartal': 61,
  'kartal-pendik': 62,
  'kavacık mahallesi': 63,
  'kayabaşı mahallesi': 64,
  'kaynarca': 65,
  'kayışdağı': 66,
  'kazlıçeşme': 67,
  'kağıthane': 68,
  'kumburgaz': 69,
  'kumkapı': 70,
  'kurtköy': 71,
  'küçükbakkalköy': 72,
  'küçükçekmece': 73,
  'laleli': 74,
  'levent': 75,
  'maltepe': 76,
  'maslak': 77,
  'mecidiyeköy': 78,
  'merter': 79,
  'moda': 80,
  'nişantaşı': 81,
  'ortaköy': 82,
  'osmanbey': 83,
  'pendik': 84,
  'rasimpaşa': 85,
  'sanayi mahallesi': 86,
  'sancaktepe': 87,
  'sarıyer': 88,
  'silivri': 89,
  'sirkeci': 90,
  'suadiye': 91,
  'sultanahmet': 92,
  'sultanahmet-sirkeci': 93,
  'taksim': 94,
  'tarabya': 95,
  'tophane': 96,
  'topkapı': 97,
  'tuzla': 98,
  'yenibosna': 99,
  'yeşilköy': 100,
  'yıldız': 101,
  'zeytinburnu': 102,
  'çağlayan mahallesi': 103,
  'ümraniye': 104,
  'üsküdar': 105,
  'şile': 106,
  'şirinevler mahallesi': 107,
  'şişli': 108},
 'secenek': {'açık büfe kahvaltı': 0,
  'her sabah kahve/hamur işi ürünler': 1,
  'izole oda kahvaltı': 2,
  'oda kahvaltı': 3,
  'sadece oda': 4,
  'ücretsiz akşam yemeği': 5}}

In [29]:
df.isnull().sum()   #bos deger var mı

konum      0
secenek    0
fiyat      0
dtype: int64

In [30]:
X = df.drop("fiyat",axis =1)
y = df["fiyat"]

In [31]:
 from sklearn.linear_model import LinearRegression, Ridge, Lasso ,ElasticNet
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import time
import warnings
warnings.filterwarnings('ignore')

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=37)

models = [
    LinearRegression(), Ridge(), Lasso() ,ElasticNet(),
    DecisionTreeRegressor(),
    RandomForestRegressor(),
    XGBRegressor()
]

scores_df = pd.DataFrame(columns=['Model','Score','Time'])

for model in models:
    start = time.time()
    model.fit(X_train,y_train)
    end = time.time()
    
    
    scores_df = scores_df._append({'Model':type(model).__name__,'Score':model.score(X_test,y_test),
      'Time':end-start},ignore_index=True)
    print(f"{type(model).__name__} - {model.score(X_test,y_test)}")

LinearRegression - -0.011839231779944503
Ridge - -0.011849644005438753
Lasso - -0.011860149841413259
ElasticNet - -0.013532260273904528
DecisionTreeRegressor - -0.13032358807171973
RandomForestRegressor - -0.040776825626428925
XGBRegressor - -0.17708912727038006

In [32]:
scores_df

                   Model     Score      Time
0       LinearRegression -0.011839  0.096733
1                  Ridge -0.011850  0.041480
2                  Lasso -0.011860  0.073885
3             ElasticNet -0.013532  0.005991
4  DecisionTreeRegressor -0.130324  0.157136
5  RandomForestRegressor -0.040777  0.541463
6           XGBRegressor -0.177089  0.300926

In [33]:
scores_df.sort_values(by="Score",ascending = False)

                   Model     Score      Time
0       LinearRegression -0.011839  0.096733
1                  Ridge -0.011850  0.041480
2                  Lasso -0.011860  0.073885
3             ElasticNet -0.013532  0.005991
5  RandomForestRegressor -0.040777  0.541463
4  DecisionTreeRegressor -0.130324  0.157136
6           XGBRegressor -0.177089  0.300926

In [34]:
best = LinearRegression()
best.fit(X_train,y_train)

LinearRegression()

In [35]:
import joblib
joblib.dump(best, 'linear_regression_model.pkl')

['linear_regression_model.pkl']